### ISSUE TITLE
Cannot find GitLab Remote

### ISSUE THREAD

**Issue by PavlikPolivka** [PavlikPolivka/GitLabProjects#33]

**Comment by pl1zahd** [comment]
I still get this error with Version **1.3.5**.

We are using GitLab with an HTTPS URL and an explicit Port Number in the URL if that helps you finding the Problem.

**Comment by PavlikPolivka** [comment]
Hi 
Can you post what your GitLab server is in URL
And what are your remotes in the project (git remote -v)
It would help to bugfix this issue.
-----------
Unit test for all URL combinations should be created to prevent this in the future.

**Comment by pl1zahd** [comment]
Hi,
I can give you an RegEx of the URL since the URL should not be visible to the world ;)

GitLab URL:
https://[a-z\.-]+:[0-9]+

For the remotes there are some differences:
First we use **ssh** and second we use another **port**:

ssh://[a-z]+@[a-z\.-]+:[0-9]+/[a-z]+/[a-z]+\.git

**My guess right now is, when you changed/optimized the RegEx for the URL you didn't think of a '-' that could be in the URL.** 

When I use the RegEx in the File [GitLabUtil.java](https://github.com/PavlikPolivka/GitLabProjects/blob/develop/src/main/java/com/ppolivka/gitlabprojects/util/GitLabUtil.java) in line [95](https://github.com/PavlikPolivka/GitLabProjects/blob/develop/src/main/java/com/ppolivka/gitlabprojects/util/GitLabUtil.java#L95) with our URL the matches look like this:

>   1 => 'https://',
  2 => '',
  3 => '[a-z\.]+',
  4 => '',
  5 => '[a-z\.-]+:[0-9]+',

If I change the RegEx to `"(\\w+://)(.+@)*([\\w\\d\\.-]+)(:[\\d]+){0,1}/*(.*)|(.+@)*([\\w\\d\\.-]+):(.*)"` the matches look like this:

>  1 => 'https://',
  2 => '',
  3 => '[a-z\.-]+',
  4 => ':[0-9]+',
  5 => '',

Maybe there are more lines where you use that RegEx but that's the first that I found when you fixes #33 the first time around.

**Comment by PavlikPolivka** [comment]
Thank you for this. Yes I completely missed '-' as valid url character. 
I have modified that regex and added [unit test](https://github.com/PavlikPolivka/GitLabProjects/blob/develop/src/test/java/com/ppolivka/gitlabprojects/util/GitLabUtilTest.java#L26) for this.

I have deployed this fix to jetbrains repo.
