### ISSUE TITLE
Use OAuth to authenticate to GitLab instead of Private Key

### ISSUE THREAD

**Issue by tstackhouse** [PavlikPolivka/GitLabProjects#60]
I don't feel comfortable providing a plugin with my private key, is it possible to use OAuth to authenticate instead?

**Comment by PavlikPolivka** [comment]
Hi not right now, but you are not providing your private key but gitlab private token. 
https://docs.gitlab.com/ee/api/README.html#private-tokens
You can generate a private token for each application and with this token API can do only the same thinks as with oath token. You can delete or invalidate that token in gitlab ui and plugin cannot do anything.
It's effectivly same think as oath but token is generated by you in browser not by the plugin.
There is no plan for doing the oatuh support since it does not make sense while tokens exists.
Closing this issue.

**Comment by tstackhouse** [comment]
Thanks for the quick reply!  I looked into it, and in gitlab versions >= 8.8, they have added "Personal Access Tokens" (https://docs.gitlab.com/ee/api/README.html#personal-access-tokens) which are identical to the private tokens, but can be generated, tracked, and managed on a per-application basis and function identically to the Private Tokens.  I was able to create one and use it to access my gitlab.com account perfectly.

Thanks for making this tool!
