### ISSUE TITLE
Slow Loading data

### ISSUE THREAD

**Issue by SillyV** [PavlikPolivka/GitLabProjects#91]
When I click create merge request, the Loading takes about 40 seconds.

what could cause such an issue? is it the size of the projects? the amount of projects on gitlab? or is it just the general slowness of Gitlab api?

My company has about 156 project on Gitlab.
and I tested the plugin on small and large projects and it worked slow on all of them.

if it is caused by the amount of projects should I limit my access to only the projects that I actively use?

**Comment by PavlikPolivka** [comment]
Hi,

When you click on create merge request plugin needs to find the correct gitlab project from your remotes.
How this is done that I does a API call to list all projects current user has access to and does regex match on all possible http or ssh combinations of remotes. 
This whole process can take forever if there is a lot of projects.
This is due to multiple factors... gitlab api is not super responsive with that amount of projects and there is a lot of combinations to test to determine the correct repo (people do crazy stuff with their gitlab installations).

There is mechanism in place that plugin tries to save the correct gitlab project id into the project settings of project (xml file inside .idea folder). But this value is never read and it goes over all the projects with every merge request.

I will try to fix this so that it should only take a long time for first time.

I this will not help you I would suggest reducing number of projects.

**Comment by PavlikPolivka** [comment]
I released fix for caching. Hope this helps.

**Comment by SillyV** [comment]
Thanks a lot! I will give it a go tomorrow at the office!
